// frontend/src/app/routes/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RegistrationService } from './registration.service';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent implements OnInit {
  registrationForm: FormGroup;
  error: string | null = null;

  constructor(private fb: FormBuilder, private registrationService: RegistrationService) {
    this.registrationForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]]
    });
  }

  ngOnInit(): void {}

  onSubmit() {
    if (this.registrationForm.valid) {
      const formData = this.registrationForm.value;

      this.registrationService.register(formData).subscribe(
        response => {
          console.log(response);
          // Handle success, e.g., show a success message or redirect to another page
          this.error = null; // Clear any existing error messages on success
        },
        err => {
          console.error(err);
          // Using the error message passed from the service
          this.error = err || "There was an error with registration. Please try again.";
        }
      );
    } else {
      this.error = "All fields are required!";
    }
  }
}

<div>
  <h1>Registration Page</h1>
  <form [formGroup]="registrationForm" (ngSubmit)="onSubmit()">

    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" id="username" formControlName="username" class="form-control">
      <div *ngIf="registrationForm.controls['username'].invalid && registrationForm.controls['username'].touched">
        Username is required.
      </div>
    </div>

    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" id="password" formControlName="password" class="form-control">
      <div *ngIf="registrationForm.controls['password'].invalid && registrationForm.controls['password'].touched">
        Password is required.
      </div>
    </div>

    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" id="email" formControlName="email" class="form-control">
      <div *ngIf="registrationForm.controls['email'].invalid && registrationForm.controls['email'].touched">
        Valid email is required.
      </div>
    </div>

    <button type="submit" [disabled]="registrationForm.invalid">Register</button>
  </form>
  <div *ngIf="error">{{ error }}</div>
</div>

// frontend/src/routes/Registration.jsx
// eslint-disable-next-line no-unused-vars
import React, { useState } from "react";
import axios from "axios";

function Registration() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");

  const handleUsernameChange = (event) => {
    setUsername(event.target.value);
  };

  const handlePasswordChange = (event) => {
    setPassword(event.target.value);
  };

  const handleEmailChange = (event) => {
    setEmail(event.target.value);
  };

  const handleSubmit = async (event) => {
    event.preventDefault();

    try {
      const response = await axios.post("http://localhost:8000/api/register/", {
        username,
        password,
        email,
      });
      console.log(response.data);
      // Handle success, e.g., show a success message or redirect to another page
    } catch (error) {
      console.error(error);
      // Handle error, e.g., show an error message
    }
  };

  return (
    <div>
      <h1>Registration Page</h1>
      <form onSubmit={handleSubmit}>
        <label>
          Username:
          <input type="text" value={username} onChange={handleUsernameChange} />
        </label>
        <br />
        <label>
          Password:
          <input type="password" value={password} onChange={handlePasswordChange} />
        </label>
        <br />
        <label>
          Email:
          <input type="email" value={email} onChange={handleEmailChange} />
        </label>
        <br />
        <button type="submit">Register</button>
      </form>
    </div>
  );
}

export default Registration;
