// frontend/src/routes/Login.jsx
// src/Login.jsx
import { useState } from "react";
import axios from "axios";

function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(null);

  const handleUsernameChange = (event) => {
    setUsername(event.target.value);
  };

  const handlePasswordChange = (event) => {
    setPassword(event.target.value);
  };

  const handleSubmit = async (event) => {
    event.preventDefault();

    try {
      const response = await axios.post("http://localhost:8000/api/login/", {
        username,
        password,
      });
      console.log(response.data);
      // Handle successful login, e.g., redirect to another page
    } catch (error) {
      console.error(error);
      setError("Invalid credentials. Please try again.");
    }
  };

  return (
    <div>
      <h1>Login Page</h1>
      <form onSubmit={handleSubmit}>
        <label>
          Username:
          <input type="text" value={username} onChange={handleUsernameChange} />
        </label>
        <br />
        <label>
          Password:
          <input type="password" value={password} onChange={handlePasswordChange} />
        </label>
        <br />
        <button type="submit">Login</button>
      </form>
      {error && <div>{error}</div>}
    </div>
  );
}

export default Login;

// frontend/src/app/routes/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LoginService } from './login.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent {
  loginForm: FormGroup;
  error: string | null = null;

  constructor(private fb: FormBuilder, private loginService: LoginService) {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
    });
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      const { username, password } = this.loginForm.value;

      this.loginService.login(username, password).subscribe(
        response => {
          console.log(response);
          // Handle successful login, e.g., redirect to another page
          this.error = null;
        },
        err => {
          console.error(err);
          this.error = 'Invalid credentials. Please try again.';
        }
      );
    }
  }
}

<div>
  <h1>Login Page</h1>
  <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">

    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" id="username" formControlName="username">
      <div *ngIf="loginForm.controls['username'].invalid && loginForm.controls['username'].touched">
        Username is required.
      </div>
    </div>

    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" id="password" formControlName="password">
      <div *ngIf="loginForm.controls['password'].invalid && loginForm.controls['password'].touched">
        Password is required.
      </div>
    </div>

    <button type="submit" [disabled]="loginForm.invalid">Login</button>
  </form>

  <div *ngIf="error">{{ error }}</div>
</div>
